---
title: "SS154 Final Code"
output: html_document
date: '2023-04-16'
---
```{r}
# install.packages("Synth")
library(Synth)
```


```{r}
data = read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vR4WXnBGhkJZW8aBc6NM4fHGtoByhbLy_oSeFLW0Mm4K3CpBe_CQqf6JkxqtyxOzBZyQE0uP-fvL6dq/pub?gid=0&single=true&output=csv")
gdp_percapita <- data$gdp / data$population
data$gdp_percapita <- gdp_percapita

#data$country <- as.character(data$country)
#data$unemployment <- as.numeric(data$unemployment_rate)
head(data)

# get the summary of the dataset
summary_data <- summary(data)
# export summary in a format that can be used in a latex document
library(xtable)
table_data <- xtable(summary_data)
print(table_data)
print(table_data, type = "latex")
```

```{r}
```

```{r}
```

```{r}
treated_unit <- "UK"
control_units <- c("Ireland", "New Zealand", "Switzerland", "France", "Belgium", "Netherlands", "Spain", "Japan", "Mexico","Algeria")

dataprep.out <-
    dataprep(foo = data,
             predictors = c("unemployment_rate" , "population" , "inflation_rate", "democarcy_level", "total_inland_transport_infrastructure_investment_per_GDP"),
             predictors.op = "mean",
             time.predictors.prior = 1990:2005,
             dependent = "gdp",
             unit.variable = "id",
             unit.names.variable = "country",
             time.variable = "year",
             special.predictors = list(
                list("gdp_percapita" , 1990 , "mean"),
                list("gdp_percapita" , 1995 , "mean"),
            #      list("gdp_percapita" , 2003 , "mean"),
            #      list("gdp_percapita" , 2004 , "mean"),
                 list("gdp_percapita" , 2005 , "mean")
            #      list("gdp_percapita" , 2006 , "mean"),
            #      list("gdp_percapita" , 2007 , "mean"),
            #      list("gdp_percapita" , 2008 , "mean"),
            #      list("gdp" , 2003 , "mean"),
            #      list("gdp" , 2004 , "mean"),
            #      list("gdp" , 2005 , "mean"),
            #      list("gdp" , 2006 , "mean"),
            #      list("gdp" , 2007 , "mean"),
            #      list("gdp" , 2008 , "mean"),
            #      list("total_inland_transport_infrastructure_investment_per_GDP" , 2003 , "mean"),
            #      list("total_inland_transport_infrastructure_investment_per_GDP" , 2004 , "mean"),
            #      list("total_inland_transport_infrastructure_investment_per_GDP" , 2005 , "mean")
             ),
             treatment.identifier = 1,
             controls.identifier = c(2:11),
             time.optimize.ssr = 1990:2005,
             time.plot = 1990:2015)
```

```{r}
gaps <- dataprep.out$Y1plot - (dataprep.out$Y0plot %*% synth.out$solution.w)
gaps[1:5, 1]

synth.out <- synth(data.prep.obj = dataprep.out)
synth.tables <- synth.tab(dataprep.res = dataprep.out,
                          synth.res = synth.out
)
synth.tables$tab.w[1:10, ]
```


```{r}
synth.tables$tab.pred[1:3, ]
synth.tables$tab.pred[4:6, ]
```

```{r}
# jpeg(file="sc_plot.jpeg")
sc_plot <- path.plot(synth.res = synth.out,
          dataprep.res = dataprep.out,
          Ylab = "GDP",
          Xlab = "Year",
          Legend = c("UK","synthetic UK"),
          Legend.position = "bottomright"
)
abline(v=2005, col="red", lty=2)
abline(v=2012, col="#110b75", lty=2)
# dev.off()
sc_plot
```

```{r}
gaps <- dataprep.out$Y1plot - (dataprep.out$Y0plot %*% synth.out$solution.w)
mspepost <- mean((gaps[16:25, 1])^2)
mspepre <- mean((gaps[1:15, 1])^2)
msperatio = mspepost/mspepre
msperatio
```

```{r}
store <- matrix(NA,length(1990:2015),10)
colnames(store) <- unique(data$country)[-1]

# run placebo test
for(iter in 2:11) {
 dataprep.out <-
              dataprep(foo = data,
                       predictors = c("unemployment_rate" , "population" , "inflation_rate", "democarcy_level", "total_inland_transport_infrastructure_investment_per_GDP"),
                       predictors.op = "mean" ,
                       time.predictors.prior = 1990:2012,
                    #    special.predictors = list(
                    #      list("gdpcap" , 1960:1969 , "mean"),
                    #      list("sec.agriculture" ,      seq(1961,1969,2), "mean"),
                    #      list("sec.energy" ,           seq(1961,1969,2), "mean"),
                    #      list("sec.industry" ,         seq(1961,1969,2), "mean"),
                    #      list("sec.construction" ,     seq(1961,1969,2), "mean"),
                    #      list("sec.services.venta" ,   seq(1961,1969,2), "mean"),
                    #      list("sec.services.nonventa" ,seq(1961,1969,2), "mean"),
                    #      list("popdens", 1969, "mean")
                    #                             ),
                       dependent = "gdp",
                       unit.variable = "id",
                       unit.names.variable = "country",
                       time.variable = "year",
                       treatment.identifier = iter,
                       controls.identifier = c(2:11)[-iter+1],
                       time.optimize.ssr = 1990:2012,
                       time.plot = 1990:2015
                       )


### Below is that extra bit of custom data-manipulation that you would ordinarily NEVER have to do-- Abadie did it.

#  dataprep.out$X1["school.high",] <-
#    dataprep.out$X1["school.high",] + dataprep.out$X1["school.post.high",]
#  dataprep.out$X1 <-
#    as.matrix(dataprep.out$X1[-which(rownames(dataprep.out$X1)=="school.post.high"),])
#  dataprep.out$X0["school.high",] <-
#    dataprep.out$X0["school.high",] + dataprep.out$X0["school.post.high",]
#  dataprep.out$X0 <-
#    dataprep.out$X0[-which(rownames(dataprep.out$X0)=="school.post.high"),]

#  lowest  <- which(rownames(dataprep.out$X0)=="school.illit")
#  highest <- which(rownames(dataprep.out$X0)=="school.high")

#  dataprep.out$X1[lowest:highest,] <-
#   (100*dataprep.out$X1[lowest:highest,]) /
#    sum(dataprep.out$X1[lowest:highest,])
#  dataprep.out$X0[lowest:highest,] <-
#    100*scale(dataprep.out$X0[lowest:highest,],
#              center=FALSE,
#              scale=colSums(dataprep.out$X0[lowest:highest,])
#   )
     
## THIS ENDS THE data manipulation part. Synth() runs:
# run synth
synth.out <- synth(
                   data.prep.obj = dataprep.out,
                   method = "BFGS"
                   )

# store gaps
store[,iter-1] <- dataprep.out$Y1plot - (dataprep.out$Y0plot %*% synth.out$solution.w)
}


# now make figure
storage <- store
rownames(storage) <- 1990:2015

# Set bounds in gaps storage: set up the gaps plot
gap.start     <- 1
gap.end       <- nrow(storage)
years         <- 1990:2015
gap.end.pre  <- which(rownames(storage)=="2012")

#  MSPE Pre-Treatment -- this is where we eliminate bad placebo models... just like in the California paper...
# Exclude states with 5 times higher MSPE than basque
mse        <-             apply(storage[ gap.start:gap.end.pre,]^2,2,mean)
data.mse <- as.numeric(mse[10])
storage <- storage[,mse<5*data.mse]
Cex.set <- .75

# Plot
plot(years,storage[gap.start:gap.end,which(colnames(storage)=="UK")],
     ylim=c(-3,3),xlab="year",
     xlim=c(1990,2015),ylab="gap in GDP",
     type="l",lwd=2,col="black",
     xaxs="i",yaxs="i")

# Add lines for control states
for (i in 1:ncol(storage)) { lines(years,storage[gap.start:gap.end,i],col="gray") }

## Add Basque Line
lines(years,storage[gap.start:gap.end,which(colnames(storage)=="UK")],lwd=2,col="black")

# Add grid
abline(v=2012,lty="dotted",lwd=2)
abline(h=0,lty="dashed",lwd=2)
legend("bottomright",legend=c("UK","control regions"),
lty=c(1,1),col=c("black","gray"),lwd=c(2,1),cex=.8)
arrows(2005,-1.5,1990.5,-1.5,col="black",length=.1)
text(2000,-1.5,"Olympics Onset",cex=Cex.set)
abline(v=1990)
abline(v=2015)
abline(h=-3)
abline(h=3)


mse.pre <- apply(storage[ gap.start:gap.end.pre, ]^2,2,mean)
mse.pre
## MSE Post---I had to write this myself
post.tmt.years <- c((gap.end.pre+1):gap.end)
mse.post <- apply(storage[post.tmt.years, ]^2,2,mean)
cat("\n\n")

mse.post

mse.post/mse.pre

sort(mse.post/mse.pre)

hist(mse.post/mse.pre, breaks = 10)
```

```{r}
gaps.plot(synth.res = synth.out,
          dataprep.res = dataprep.out,
          Ylab = "GDP",
          Xlab = "Year",
          Main = NA
)
```

```{r}
require(tidysynth)

data %>% dplyr::glimpse()


data_out <-
  
  data %>%
  
  # initial the synthetic control object
  synthetic_control(outcome = gdp, # outcome
                    unit = country, # unit index in the panel data
                    time = year, # time index in the panel data
                    i_unit = "UK", # unit where the intervention occurred
                    i_time = 2012, # time period when the intervention occurred
                    generate_placebos=T # generate placebo synthetic controls (for inference)
                    ) %>%
  
  # Generate the aggregate predictors used to fit the weights
  
  # average log income, retail price of cigarettes, and proportion of the
  # population between 15 and 24 years of age from 1980 - 1988
  generate_predictor(time_window = 1990:2012,
                     unemploy_rate = mean(unemployment_rate, na.rm = T),
                     popu = mean(population, na.rm = T),
                     inf_rate = mean(inflation_rate, na.rm = T),
                     demo_level = mean(democarcy_level, na.rm = T),
                     total_inland_transport_infrastructure_investment_per_GDP = mean(total_inland_transport_infrastructure_investment_per_GDP, na.rm = T)) %>%
                    #  ln_income = mean(lnincome, na.rm = T),
                    #  ret_price = mean(retprice, na.rm = T),
                    #  youth = mean(age15to24, na.rm = T)) %>%
  
#   # average beer consumption in the donor pool from 1984 - 1988
#   generate_predictor(time_window = 1984:1988,
#                      beer_sales = mean(beer, na.rm = T)) %>%
  
#   # Lagged cigarette sales 
#   generate_predictor(time_window = 1975,
#                      cigsale_1975 = cigsale) %>%
#   generate_predictor(time_window = 1980,
#                      cigsale_1980 = cigsale) %>%
#   generate_predictor(time_window = 1988,
#                      cigsale_1988 = cigsale) %>%
  
  
  # Generate the fitted weights for the synthetic control
  generate_weights(optimization_window = 1990:2012, # time to use in the optimization task
                   margin_ipop = .02,sigf_ipop = 7,bound_ipop = 6 # optimizer options
  ) %>%
  
  # Generate the synthetic control
  generate_control()

data_out %>% plot_trends()
```

