---
title: "SS156 Final Code"
output: html_document
date: '2023-04-16'
---
```{r}
install.packages("Synth")
library(Synth)
```


```{r}
data = read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vR4WXnBGhkJZW8aBc6NM4fHGtoByhbLy_oSeFLW0Mm4K3CpBe_CQqf6JkxqtyxOzBZyQE0uP-fvL6dq/pub?gid=0&single=true&output=csv")
gdp_percapita <- data$gdp / data$population
data$gdp_percapita <- gdp_percapita

#data$country <- as.character(data$country)
#data$unemployment <- as.numeric(data$unemployment_rate)
head(data)

```

```{r}
treated_unit <- "UK"
control_units <- c("Ireland", "New Zealand", "Switzerland", "France", "Belgium", "Netherlands", "Spain", "Japan", "Mexico","Algeria")

dataprep.out <-
    dataprep(foo = data,
             predictors = c("unemployment_rate" , "population" , "inflation_rate", "democarcy_level", "total_inland_transport_infrastructure_investment_per_GDP", "percentage_of_tourism"),
             predictors.op = "mean",
             time.predictors.prior = 1990:2005,
             dependent = "gdp",
             unit.variable = "id",
             unit.names.variable = "country",
             time.variable = "year",
             special.predictors = list(
                list("gdp_percapita" , 1990 , "mean"),
                list("gdp_percapita" , 1995 , "mean"),
            #      list("gdp_percapita" , 2003 , "mean"),
            #      list("gdp_percapita" , 2004 , "mean"),
                 list("gdp_percapita" , 2005 , "mean")
            #      list("gdp_percapita" , 2006 , "mean"),
            #      list("gdp_percapita" , 2007 , "mean"),
            #      list("gdp_percapita" , 2008 , "mean"),
            #      list("gdp" , 2003 , "mean"),
            #      list("gdp" , 2004 , "mean"),
            #      list("gdp" , 2005 , "mean"),
            #      list("gdp" , 2006 , "mean"),
            #      list("gdp" , 2007 , "mean"),
            #      list("gdp" , 2008 , "mean"),
            #      list("total_inland_transport_infrastructure_investment_per_GDP" , 2003 , "mean"),
            #      list("total_inland_transport_infrastructure_investment_per_GDP" , 2004 , "mean"),
            #      list("total_inland_transport_infrastructure_investment_per_GDP" , 2005 , "mean")
             ),
             treatment.identifier = 1,
             controls.identifier = c(2:11),
             time.optimize.ssr = 1990:2005,
             time.plot = 1990:2015)
```

```{r}
synth.out <- synth(data.prep.obj = dataprep.out)
synth.tables <- synth.tab(dataprep.res = dataprep.out,
                          synth.res = synth.out
)
synth.tables$tab.w[1:10, ]
```


```{r}
synth.tables$tab.pred[1:3, ]
synth.tables$tab.pred[4:6, ]
```

```{r}
path.plot(synth.res = synth.out,
          dataprep.res = dataprep.out,
          Ylab = "GDP",
          Xlab = "Year",
          Legend = c("UK","synthetic UK"),
          Legend.position = "bottomright"
)
# add line x=2007
abline(v=2005, col="red", lty=2)
abline(v=2012, col="#110b75", lty=2)
# save plot
library(ggplot2)
ggsave("path_plot1.png", width = 10, height = 6)
```

```{r}
```

```{r}
gaps.plot(synth.res = synth.out,
          dataprep.res = dataprep.out,
          Ylab = "GDP",
          Xlab = "Year",
          Main = NA
)
```

